### PR TITLE
Fun stuff idea

### PR DESCRIPTION
**Pull request by baiwangyek**
Everyone split into teams of 4-5 with a small prize (like stickers/ code swag etc) for the winning team.

### CODE REVIEW

**Comment by sirmews** [comment]
Great idea! Do you have an idea of the kind of questions to ask?

**Comment by baiwangyek** [comment]
I'm thinking a mix of technical and little known facts about CSS. For the technical questions, you can show a block of CSS code and then ask the floor to predict the final outcome. Eg : 
`.example {display: inline-block; margin: 0 auto; padding-top: 40px;}` - which among the four images best fit the code block.

Maybe we can crowd source the questions?

**Comment by sirmews** [comment]
Yea that sounds doable. Neither @teriu or I have the time at the moment to really come up with these so crowd sourcing would be good.

There's also this https://github.com/flukeout/css-diner
Which can be forked and made into a customised interactive experience. 

Would you like to take lead on this @baiwangyek ?

**Comment by baiwangyek** [comment]
@raonav That site is really cool. Yea, I don't mind :) I'm still finishing up my portfolio website (hopefully it'll be done in 1-2 weeks) but after that I'm as free as a butterfly haha I'm thinking of making a CSS trivia question inputer website where members of the slack can participate. And the user who submitted the most CSS trivia question will have bonus points for his/her team on the night.

**Comment by sirmews** [comment]
Sounds like an idea. Looking forward to seeing your portfolio site when it's up.

**Pull request merged**
